grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2


model_selection:
module_0:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: sqrt
      n_estimators: 3
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 10
      - 50
      - 100



module_1:
    class: CatBoostClassifier
    module: catboost
    params:
      iterations: 10
      learning_rate: 0.1
      depth: 12
      l2_leaf_reg : 3
    search_param_grid:
      iterations:
      - 10
      - 50
      - 100
      learning_rate:
      - 0.01
      - 0.1
      - 0.2
      depth:
      - 10
      - 12
      l2_leaf_reg:
      - 3
      - 5
      


module_2:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      learning_rate: 0.1
      n_estimators: 100
    search_param_grid:
      learning_rate:
      - 0.01
      - 0.1
      - 0.2
      n_estimators:
      - 50
      - 100
      - 150