columns:
  airline: object
  overall: float64
  author: object
  review_date: int64
  customer_review: object
  aircraft: object
  traveller_type: object
  cabin: object
  route: object
  date_flown: int64
  seat_comfort: float64
  cabin_service: float64
  food_bev: float64
  entertainment: float64
  ground_service: float64
  value_for_money: float64
  recommended: object

numerical_columns:
  - overall
  - review_date
  - date_flown
  - seat_comfort
  - cabin_service
  - food_bev
  - entertainment
  - ground_service
  - value_for_money

categorical_columns:
  - airline
  - author
  - customer_review
  - aircraft
  - traveller_type
  - cabin
  - route
  - recommended

dtypes:
  airline: "object"
  overall: "float64"
  author: "object"
  review_date: "int64"
  customer_review: "object"
  aircraft: "object"
  traveller_type: "object"
  cabin: "object"
  route: "object"
  date_flown: "int64"
  seat_comfort: "float64"
  cabin_service: "float64"
  food_bev: "float64"
  entertainment: "float64"
  ground_service: "float64"
  value_for_money: "float64"
  recommended: "object"




# Datatransformation
num_features:
- overall
- seat_comfort
- food_bev
- sentiment_score



or_columns:   # columns to be ordinal encoded like ['SEX'/Gender] means Yes or No
- airline
- cabin
oh_columns: []   # columns to be one hot encoded like EDUCATION', 'MARRIAGE']


transform_columns:
- sentiment_score


drop_columns:
- customer_review
- author
- review_date
- value_for_money
- cabin_service
